jobtriage/jobtriage

config/application.rb, config/mongoid.yml, frontend/src/service/APIService.js
=> Add CD changes

.github/ISSUE_TEMPLATE/1.bug.md, .github/ISSUE_TEMPLATE/2.feature.md, .github/PULL_REQUEST_TEMPLATE.md
=> Add Issue and PR templates

README.md
=> Add API document

Gemfile, Gemfile.lock, test/test_helper.rb
=> Add minitest reporter

app/controllers/auth_controller.rb, config/routes.rb, frontend/src/Components/AccountDetails/AccountDetails.js, frontend/src/Material-UI/Components/Button/Button.js, frontend/src/service/APIService.js
- API for logout
- UI implementation
Fixes #21
=> Add logout API and front-end implementation

test/controllers/applications_controller_test.rb, test/models/application_test.rb, test/test_helper.rb
Added better assertion of JSON response keys.
=> Improve test assertion

app/controllers/auth_controller.rb, frontend/src/Containers/App/App.js, frontend/src/Containers/Onboarding/Login/LoginPage.js, lib/json_web_token.rb
=> Fix account details blank after login issue

app/controllers/auth_controller.rb, app/controllers/notes_controller.rb, app/models/application.rb, app/models/note.rb, config/routes.rb, frontend/src/Containers/App/App.js, frontend/src/Containers/Onboarding/Login/LoginPage.js, lib/json_web_token.rb, test/controllers/notes_controller_test.rb, test/fixtures/notes.yml, test/models/note_test.rb, test/test_helper.rb
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Add notes API

frontend/src/Containers/Dashboard/Dashboard.js
=> Fix code climate issues

app/controllers/notes_controller.rb, app/models/application.rb, app/models/note.rb, config/routes.rb, test/controllers/notes_controller_test.rb, test/models/note_test.rb, test/test_helper.rb
Used embedded document for notes before, now changed to separate document.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Add notes enhancements

README.md
Improve the documentation regarding the server in the local environment.
Fixes #58
=> [Docs]: Imrove documentation

frontend/src/Components/Navbar/NavBar.js, frontend/src/Components/Navbar/NavBar.module.scss
=> [NavBar]: Fix bug for active style

frontend/src/Components/AccountDetails/AccountDetails.js, frontend/src/Components/LandingPage/Header/Header.js, frontend/src/Components/LandingPage/LandingBody/LandingBody.js, frontend/src/Components/LandingPage/LandingPage.js
=> Add eslint issue fix

frontend/package.json, frontend/src/Components/AccountDetails/AccountDetails.js, frontend/src/Components/LandingPage/Header/Header.js, frontend/src/Components/LandingPage/LandingBody/LandingBody.js, frontend/src/Components/index.js, frontend/src/Containers/App/App.js, frontend/src/Containers/Dashboard/AddJob/AddJob.js, frontend/src/Containers/Dashboard/Dashboard.js, frontend/src/Containers/Dashboard/viewjob/ViewJob.js, frontend/src/Containers/Onboarding/Login/LoginPage.js, frontend/src/Containers/Onboarding/Signup/SignupPage.js, frontend/src/Material-UI/Components/AppBar/AppBar.js, frontend/src/Material-UI/Components/Button/Button.js, frontend/src/Material-UI/Components/Input/Input.js, frontend/src/Material-UI/Components/Select/Select.js, frontend/src/Material-UI/Components/Typography/Typography.js, frontend/src/Material-UI/Components/index.js, frontend/src/Material-UI/import/index.js, frontend/src/Material-UI/theme/index.js, frontend/src/index.js
=> Fix Eslint Errors

frontend/src/Components/AccountDetails/AccountDetails.js, frontend/src/Components/AccountDetails/AccountDetails.module.scss, frontend/src/Components/NavBar/NavBar.js, frontend/src/Containers/Dashboard/Dashboard.js, frontend/src/Containers/Dashboard/Dashboard.module.scss
Enhanced navbar so that margin left need not to be added for each component 
=> Add navbar enhancements

frontend/src/Containers/App/App.js, frontend/src/Containers/Dashboard/AddJob/AddJob.js, frontend/src/Containers/Dashboard/Dashboard.js, frontend/src/Containers/ViewJob/BaiscDetails.js, frontend/src/Containers/ViewJob/ViewJob.js, frontend/src/Material-UI/Components/Toast/Toast.js, frontend/src/Material-UI/Components/index.js, frontend/src/index.js, frontend/src/store/context.js
Added toast component to show notifications.
Usage:
```js
import { useToast } from '../../../store/context';
const showToast = useToast();
showToast('Job application added successfully');
```
Fixes #71
=> [Toast]: Add Component for Showing Brief Message

app/controllers/auth_controller.rb, frontend/src/Containers/Onboarding/Signup/SignupPage.js
Authtoken is not set during signup. Moving forward it will be set.
Fixes #78
=> Fix signup issue - AuthToken not set during signup

frontend/public/index.html, frontend/src/global-styles/index.css
.
I changed the place where the fonts is loaded. 
Fixes # (79)
Go to /dashboard without be authenticated (i think this is an issue, you can see for a moment the page)
=> Fix fonts loading - Google font is loading multiple times (#79)

.gitignore, app/controllers/application_controller.rb, app/controllers/auth_controller.rb, app/mailers/application_mailer.rb, app/mailers/user_mailer.rb, app/models/user.rb, app/views/user_mailer/welcome_email.html.erb, app/views/user_mailer/welcome_email.text.erb, config/application.rb, config/environments/development.rb, config/routes.rb, frontend/src/Containers/App/App.js, frontend/src/Containers/Onboarding/VerifiedRoute/VerifiedRoute.js, frontend/src/service/APIService.js, frontend/src/store/actions/index.js, frontend/src/store/reducers/users.js, test/mailers/previews/user_mailer_preview.rb, test/mailers/user_mailer_test.rb
Added Signup mail verification
Fixes #81
=> Add signup mail verification

CONTRIBUTING.md, README.md
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #48
=> [Docs] Add contributing guidelines

app/controllers/auth_controller.rb, app/mailers/user_mailer.rb, app/models/user.rb, app/views/user_mailer/forgot_password_email.html.erb, app/views/user_mailer/forgot_password_email.text.erb, config/routes.rb
=> Add change password and forgot password

frontend/src/Containers/App/App.js, frontend/src/Containers/Onboarding/ForgotPassword/ForgotPassword.js, frontend/src/Containers/Onboarding/Login/LoginPage.js, frontend/src/Containers/Onboarding/Login/LoginPage.module.scss, frontend/src/Containers/Onboarding/Signup/SignupPage.js, frontend/src/service/APIService.js
- Forgot password UI
- Warning about email verification in signup form.
Fixes #89
Fixes #92
=> Add forgot password UI

frontend/src/Components/AccountDetails/AccountDetails.js, frontend/src/Containers/App/App.js, frontend/src/Containers/Dashboard/Dashboard.js, frontend/src/Containers/Onboarding/ForgotPassword/ForgotPassword.js, frontend/src/Containers/Onboarding/Login/LoginPage.js, frontend/src/Containers/Onboarding/Signup/SignupPage.js, frontend/src/Containers/SelfAnalysis/SelfAnalysis.js, frontend/src/store/context.js
API usage:
```js
import { useLoader } from '../../store/context';
const showLoader = useLoader();
showLoader(true); // Show loader
showLoader(false); // Hide loader
```
Fixes #96
=> Add loader

frontend/src/Components/AccountDetails/AccountDetails.js, frontend/src/Components/PriorityMenu/PriorityMenu.js, frontend/src/Components/StatusMenu/StatusMenu.js, frontend/src/Containers/Dashboard/AddJob/AddJob.js, frontend/src/Containers/Dashboard/Dashboard.js, frontend/src/Containers/Onboarding/ForgotPassword/ForgotPassword.js, frontend/src/Containers/Onboarding/Login/LoginPage.js, frontend/src/Containers/Onboarding/Signup/SignupPage.js, frontend/src/Containers/SelfAnalysis/AddAnalysis.js, frontend/src/Containers/SelfAnalysis/SelfAnalysis.js, frontend/src/Containers/ViewJob/BasicDetails.js, frontend/src/Containers/ViewJob/Notes/AddNote.js, frontend/src/Containers/ViewJob/ViewJob.js
Fixes Typos in Labels and General Texts.
Fixes #91  with sample text
Tested Manually
=> Bug Fix - Typos 

frontend/src/Components/AccountDetails/AccountDetails.js, frontend/src/Containers/Dashboard/Dashboard.js, frontend/src/Containers/Onboarding/VerifiedRoute/VerifiedRoute.js, frontend/src/Containers/SelfAnalysis/SelfAnalysis.js, frontend/src/Containers/ViewJob/BasicDetails.js, frontend/src/Containers/ViewJob/Notes/AddNote.js, frontend/src/Containers/ViewJob/Notes/Notes.js, frontend/src/Containers/ViewJob/TimeLog/AddTimeLog.js, frontend/src/Containers/ViewJob/TimeLog/TimeLog.js, frontend/src/Containers/ViewJob/ViewJob.js
Fixes # #118 partially -  Still View Job Container needs Nav Bar. To be refactored again.
=> UI Refactor

Gemfile, Gemfile.lock, app/controllers/applications_controller.rb, app/controllers/concerns/exception_handler.rb, app/controllers/notes_controller.rb, app/controllers/timelogs_controller.rb, app/models/analysis.rb, app/models/application.rb, app/models/note.rb, app/models/pitch.rb, app/models/timelog.rb, app/models/user.rb, config/routes.rb
Adds Jbuilder for API json response
Adds Mongo Timestamps
Cleans up controller and model
=> Refactor - BE

frontend/src/Components/index.js, frontend/src/Containers/App/App.js, frontend/src/Containers/Dashboard/Dashboard.js, frontend/src/Containers/Onboarding/VerifiedRoute/VerifiedRoute.js, frontend/src/Containers/SelfAnalysis/SelfAnalysis.js, frontend/src/Containers/ViewJob/ViewJob.js, frontend/src/Material-UI/Components/Progress/CircularProgress/CircularProgress.js, frontend/src/Material-UI/Components/Progress/LinearProgress/LinearProgress.js
Adds generic loader component using Progress
Fixes #113
=> Loader UI Component 

app/controllers/application_controller.rb, app/controllers/auth_controller.rb, app/mailers/user_mailer.rb, app/models/user.rb, app/views/user_mailer/deactivation_email.html.erb, app/views/user_mailer/deactivation_email.txt.erb
Refactors Auth Controller and Builder pattern for user creation
Follows Light Controller Heavy Model pattern
#87 will be fixed  partly
Close account  involving deleting all information related to user is handled  by using dependant:destroy model callbacks
Sends an email to user once account is deleted. 
Mailers and other APIs individually test in local
=> Refactor - Auth Controller, Close account 

app/models/user.rb, frontend/src/Containers/Dashboard/Dashboard.js, frontend/src/Containers/ViewJob/ViewJob.js
Fixes #137 
- Abstracted dashboard
- Used `useLoader` Hook instead of using <HorizontalLoader> everywhere
=> Add Email verification fix

frontend/tests/acceptance/features/webUILogin/login.feature, frontend/tests/acceptance/pages/loginPage.js, frontend/tests/acceptance/step_definitions/loginContext.js
Adds e2e test for different scenarios involved in user login.
=> Add UI login acceptance test

frontend/tests/acceptance/features/webUINavigationDrawer/navigation.feature, frontend/tests/acceptance/helpers/api/user.js, frontend/tests/acceptance/pages/accountPage.js, frontend/tests/acceptance/pages/navigationPage.js, frontend/tests/acceptance/pages/selfAnalysisPage.js, frontend/tests/acceptance/step_definitions/navigationContext.js
Adds navigation drawer test for different scenarios
=> Add navigation drawer test

frontend/tests/acceptance/features/webUIDashboard/addNewJobApplication.feature, frontend/tests/acceptance/helpers/api/job_application.js, frontend/tests/acceptance/helpers/api/user.js, frontend/tests/acceptance/pages/addNewJobApplicationForm.js, frontend/tests/acceptance/pages/dashboardPage.js, frontend/tests/acceptance/step_definitions/addNewJobApplicationContext.js
This PR adds e2e tests for testing different scenarios involved in adding new job application form.
=> [Acceptance Test] Add e2e tests for scenarios adding new job application

frontend/codecept.conf.js, frontend/tests/acceptance/features/webUIDashboard/dashboard.feature, frontend/tests/acceptance/helpers/api/job_application.js, frontend/tests/acceptance/pages/dashboardPage.js, frontend/tests/acceptance/pages/updateJobApplicationPage.js, frontend/tests/acceptance/step_definitions/dashboardContext.js
- Drag and drop job applications between different job status board
- Drag and drop job applications within a job status board
- Delete job application
- Go to update job application
=> [Acceptance Test] Add dashboard e2e test

frontend/tests/acceptance/features/webUIAccount/updatePassword.feature, frontend/tests/acceptance/pages/accountPage.js, frontend/tests/acceptance/step_definitions/updatePassowrdContext.js
This pr adds the e2e tests for update account password feature.
=> Add e2e tests for update account password

frontend/tests/acceptance/features/webUIDashboard/dashboard.feature, frontend/tests/acceptance/features/webUINavigationDrawer/navigation.feature, frontend/tests/acceptance/pages/accountPage.js, frontend/tests/acceptance/pages/dashboardPage.js, frontend/tests/acceptance/pages/loginPage.js, frontend/tests/acceptance/pages/navigationPage.js, frontend/tests/acceptance/pages/selfAnalysisPage.js, frontend/tests/acceptance/step_definitions/addNewJobApplicationContext.js, frontend/tests/acceptance/step_definitions/dashboardContext.js, frontend/tests/acceptance/step_definitions/loginContext.js, frontend/tests/acceptance/step_definitions/navigationContext.js, frontend/tests/acceptance/step_definitions/updatePassowrdContext.js
=> Refactor e2e tests

frontend/src/Containers/Dashboard/AddJob/AddJob.js, frontend/src/Containers/Dashboard/Dashboard.js, frontend/src/Material-UI/Components/ButtonGroup/ButtonGroup.js, frontend/src/Material-UI/Components/index.js, frontend/src/Material-UI/import/index.js, frontend/src/service/APIService.js
Adds Location information in dashboard and in add job form.  Uses Button Group for Priority in add job form
contributes to #22
=> Adds Location Information in Dashboard

frontend/tests/acceptance/features/webUIDashboard/addNewJobApplication.feature, frontend/tests/acceptance/pages/accountPage.js, frontend/tests/acceptance/pages/addNewJobApplicationForm.js, frontend/tests/acceptance/pages/dashboardPage.js, frontend/tests/acceptance/pages/loginPage.js, frontend/tests/acceptance/pages/navigationPage.js, frontend/tests/acceptance/pages/signupPage.js, frontend/tests/acceptance/step_definitions/addNewJobApplicationContext.js, frontend/tests/acceptance/step_definitions/signupContext.js
- Change add new job application e2e tests for new ui change
- Add element wait time to 5 sec
=> Change add new job application UI test as per new UI changes

frontend/codecept.conf.js, frontend/tests/acceptance/features/webUIDashboard/addNewJobApplication.feature, frontend/tests/acceptance/features/webUIDashboard/dashboard.feature, frontend/tests/acceptance/features/webUIDashboard/notes.feature, frontend/tests/acceptance/features/webUIDashboard/updateJobApplication.feature, frontend/tests/acceptance/helpers/api/notes.js, frontend/tests/acceptance/helpers/globals.js, frontend/tests/acceptance/pages/notesPage.js, frontend/tests/acceptance/pages/timeLogPage.js, frontend/tests/acceptance/pages/updateJobApplicationPage.js, frontend/tests/acceptance/step_definitions/dashboardContext.js, frontend/tests/acceptance/step_definitions/navigationContext.js, frontend/tests/acceptance/step_definitions/notesContext.js, frontend/tests/acceptance/step_definitions/updateJobApplicationContext.js
- update job application
- add, edit and delete job notes
=> [Test Only] Add update-job-application e2e test

Gemfile, Gemfile.lock, app/controllers/users_controller.rb, app/models/user.rb, config/routes.rb, frontend/src/Components/AccountDetails/AccountDetails.js, frontend/src/service/APIService.js, frontend/tests/acceptance/pages/signupPage.js, lib/user_dump_generator.rb
Fixes #87 
[arjun (10).pdf](https://github.com/jobtriage/jobtriage/files/4875311/arjun.10.pdf)
=> Download Data - Pdf Export 

frontend/tests/acceptance/features/webUIDashboard/notes.feature, frontend/tests/acceptance/features/webUIDashboard/timeLog.feature, frontend/tests/acceptance/features/webUIDashboard/updateJobApplication.feature, frontend/tests/acceptance/helpers/api/timelog.js, frontend/tests/acceptance/helpers/calendarHelper.js, frontend/tests/acceptance/pages/signupPage.js, frontend/tests/acceptance/pages/timeLogPage.js, frontend/tests/acceptance/step_definitions/timeLogContext.js, frontend/tests/acceptance/step_definitions/updateJobApplicationContext.js
- Add timelog to job application
- Update timelog
- Delete timelog
- Google calendar redirection
=> [Test Only] Add time-log e2e test

frontend/tests/acceptance/helpers/api/job_application.js, frontend/tests/acceptance/helpers/calendarHelper.js, frontend/tests/acceptance/pages/accountPage.js, frontend/tests/acceptance/pages/addNewJobApplicationForm.js, frontend/tests/acceptance/pages/dashboardPage.js, frontend/tests/acceptance/pages/loginPage.js, frontend/tests/acceptance/pages/notesPage.js, frontend/tests/acceptance/pages/signupPage.js, frontend/tests/acceptance/pages/timeLogPage.js, frontend/tests/acceptance/pages/updateJobApplicationPage.js
This PR adds code comments and documentation, and some code refactor.
=> Add e2e tests code documentation
